name: gsl
version: 1.0.0+1
publish_to: none
description: skripsi
environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter_dotenv: ^5.0.2
  supabase_flutter: ^1.10.25
  dropdown_search: ^5.0.6
  flutter:
    sdk: flutter
  data_table_2: ^2.5.9
  http: ^0.13.3
  intl: ^0.18.0
  fl_chart: ^0.65.0
  custom_date_range_picker: ^1.0.10
  carousel_slider: ^4.2.1

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - .env
    - images/gsl_logo.png
    - images/logo_gsl.jpg
    - images/logo_gsl.png
    - images/logo_gsl_new.png
    - images/logo_gsl_crop.png
    - images/owner_icon.png
    - images/karyawan_icon.png
    - images/pelanggan_icon.png
    - images/bg_logo.png
    - images/user_profile.png
    - images/pake_h.png
    - images/karyawan_profile.png
    - images/owner_profile.png
    - images/banner_1.png
    - images/banner_4.png
    - images/banner_5.png
    - images/banner_6.png
    - images/banner_7.png
    - images/banner_7_edit.png
    - images/banner_k.png

